/** Declaration file generated by dts-gen */
export default function gql(literals: any, ...placeholders: any[]): any;

export function toInlineFragment(doc: any): any;

export namespace toInlineFragment {
  const prototype: {};
}
