language: objective-c
xcode_project: ios/Missionhub.xcodeproj
os: osx
osx_image: xcode9.2
before_install:
- brew install yarn
- yarn install
- echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
- cd ios
- unzip fastlane/lib/FacebookSDKs-iOS-4.31.1.zip -d ~/Documents/FacebookSDK
install:
- bundler install
- fastlane ios beta
env:
  global:
  - secure: Qo7WDyR6KtZnpk5ikAHSah/SdQGIP0lHU/IaCMe5XsIqHZnxPvKNy8cyUguxDqGkwPOyOqE8ZovNDQ7ZCdu0rEug9uMX/EZxoNc2Lfcps/VrUp84Hh0lYAUD1lfpn0Oz4XwVG/5yVjgtRGFdo8FNN+hf1DnbpuijhQ5g5bYYmjYy7Qbj+dxUo4FoiYxKxCunQUessvq1JWU2TfLkS1S2Rp+a/UjxyAoTuGuXisMI2fgESaYiC0Yh1L/7fRh4owR95lwQa7ox94Nloo4VPYxOvgZMoU1YV9e8FXgZ/IacKoqV0OKRxKx81T8/TSdLVQ7Z/+S6ejradLCzEEOvEPg4HPPdGzB9Mk+dkvqqhD/NzgDXOjFOU4dsb/I6+lydYVFQ2Mfgw4bfPcs34hGsdrnO1nwIyDrJXxbKeCE62WXUQhR8SM2o+MJJ5B9hdyFevwoaV2/MKrqq9GsEGVsMMMXK3cY2AyLEfu3DufEfEHmYD1+4TBpeqrqLog1lRITdzEAJGptnTXz/weyFKnBvmAzYgVMo8YAgYd2ZrvugeobA3WdkaqkiL6yqdH/PRjp+yk8uS3zdovdyLm2ZDcKjrvY8WKKglGKjEXbjjeNMLIJwgXtdiqb7396FpB7YKttB3Iw2Us9IbH2Y60A0kEGEvWE/DaIs6gY5ZQc0EsqqDo2Rrmw=
  - secure: KOzE8ukv1toXhoEuTZ6LmREb3olfEqPbd3T8GUc0pHPVi2a2hEvvG5sVDC+JnVNeykSdbpQz5gnnzbXcC+7vUrSSN7jIfOsNbiQtLKk4MGKT0bh0jci0cTHfu2gWmYGxT2xS/Vy1lDOFyOJKU1mT9G/tbuXurc1tkm5X7gI93VZJgZy8KFtKi8654Fe1KEwdeSiKittPNUlJQFqnVmihumfx093YefgoKkwP3tr7e37ooU1k0JjxiE0WYXgz2iJ0bX2rmNBBVXTFxNzJbLZaN7smSCFhmb8e7VSObT6RnI52r7hcPQ+qQAQxvKg26qvDPnLUAOqoR4AoamxO52vINZl+UyQmk4RmcL9X1fLtBz2D+rBEmbh+6MNfrwkbal/ZiB6xULNINiQJDdCcOsn8X6ra8f75x/31ohQMMztlbDUmtbNzw1KI9vKvwY6C5zQcKG2L0PI6OE7V2fKjI8K2XxglZo8px46hbxDUH4Pv9TlwbFPl6W1X6GWuLTgk7VT1Uc/UevmlRxzz412E5Yi7rAju58z6WvBUESrZH4Dikmj+wwP6bSE0/c/m+lFmfZQiVcATU6Ky9v9rMg3u4Helsnz0ikFLGxX40RitEoFAJPJfZOyezpOcJiXpUtqLPcg7FY0qbujwp15At+pFAJ8syhwjIvPXJ+uQVMXZtuGNHb4=
