language: node_js

node_js:
  - '8'

script:
  - yarn run test:coverage
  - yarn run lint

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  yarn: true
