language: objective-c
xcode_project: ios/Missionhub.xcodeproj
os: osx
osx_image: xcode9.2
before_install:
- cd ios
- echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
install:
- bundler install
- fastlane ios beta
env:
  global:
  - secure: 3XgXLnqQzlQ8nSJ/Md+UputLVneyV7C1RhUkXhu5NjJzMz0u+/HfOJTrieI7uGhp+acH3epKeIKqWQKiknEsZRFDB/VYDUfrSWr5xYbCwdGiLPz1dwqrpB6t2Fm98KjZj/9h29MjcOXiQPkyZolocmnoJrZWmJTUyt2ay61OmodVxNBc77F9Ozj6CZqzRvxuTqZbwNViaygn5rGa8EFRZU2mDqhjfbS9G4KY8H63blMi2PUbytuanKTv4FVuKXvDZ7d+PmKenQ1OLXY7O0C4c5GF8onkqWELo/iT9bWfBljyxXls0yJGKB57UBGG+eSPH6m+CmE+B1Zrivpuzjood/WqBKFyP1a3QPsVf6znvYifjelMhkKA58sJW6QPo39vMwuSi+3oolX9ndTK29CYQ9TAt5MS94wRXe2aXYFwTX+ydPA65vuCNNstmwNtq40yMkRyZABG+EocghLvjA7BPyzI8ejYeLXuYm2SbkngeT2UP5mV5N8n7EaeU897NtPic7xiLLeG60DL5eM7snu+nFeKbmfP8nz34T4dDlVwnXA7aUeax6coXGOLTBJYX49UbFYSY3Je4E4/GMFx67sqZQLi+1oSyPTZkTVK+mSpHLmDaKuNO0XYtqqG7H7mYlbkAsA9jaonA2LEx7qdhj5QAegTIuRK+Ab6YnHLkt4FWZ0=
  - secure: h/aiM+hubiwb/fanwGFr4XzDmJS1j1KBnfIyHQmZnk1Hk7fTD1YkfJqgM7AlYQ6kY7rL02tb0IXamXJrkfTPA/JXWOZhVaCdB9MlWG/1RiJVb1Jue2JbxCcmENotl1dGaRYioWr4IXeh0PF1ySBEJ4naZNK6cJFiyAflGZHM+L3jth4wleu94s/qOGSSvWn6fUNH6m0cOdnT3sETEnbR/3brfeu3fYFcdHGSMkC4O1IwVY1KYaITNk8b5aJDQX5OZygB9Xw57PpDN0u4A1IXbaEsHLtS5z8cCEiwRbWcXYcM3pPfYN01Dm35DAob05LcDfivucEgqvETcJL7rjL0yb6s+AcRkkX6PhamUvX6YbENA0AfXyYPiTletcTdZ2YtonmZGDtDttWsG8DViErsMTGKNu0FMGQVcjKoJXSnGh/HKDU0L6mnvES79+zHKWJNRywxAfOL7T9BcuDh5k4ITsjVMD80/3K+DpStLEVQ4nN9wiXOExVNOfwXpVPTQC9aH76x0Jq7YIW3QaCvXEP8U8v73BSlmFgxvt4oS+7sdpPZBzPna9uxqdoyCkoZOGUUew2fCLz/bPp/kls68uTtOLlSzjjTMGIjJe4+zngwWqbot3lLFd1fGVOAFZf9cTKSiNjCzsqFYHFLAr2r0qZjAHGBlY8nQ/AjzVFW8z1XSbc=
