export const SIGN_IN_FLOW = 'nav/SIGN_IN_FLOW';
export const SIGN_UP_FLOW = 'nav/SIGN_UP_FLOW';
export const CREATE_COMMUNITY_UNAUTHENTICATED_FLOW =
  'nav/CREATE_COMMUNITY_UNAUTHENTICATED_FLOW';
export const JOIN_BY_CODE_FLOW = 'nav/JOIN_BY_CODE_FLOW';
export const JOIN_BY_CODE_ONBOARDING_FLOW = 'nav/JOIN_BY_CODE_ONBOARDING_FLOW';
export const DEEP_LINK_JOIN_COMMUNITY_AUTHENTENTICATED_FLOW =
  'nav/DEEP_LINK_JOIN_COMMUNITY_AUTHENTENTICATED_FLOW';
export const DEEP_LINK_JOIN_COMMUNITY_UNAUTHENTENTICATED_FLOW =
  'nav/DEEP_LINK_JOIN_COMMUNITY_UNAUTHENTENTICATED_FLOW';
export const COMPLETE_STEP_FLOW = 'nav/COMPLETE_STEP_FLOW';
