export const JOIN_BY_CODE_FLOW = 'nav/JOIN_BY_CODE_FLOW';
export const JOIN_BY_CODE_ONBOARDING_FLOW = 'nav/JOIN_BY_CODE_ONBOARDING_FLOW';
export const DEEP_LINK_JOIN_COMMUNITY_AUTHENTENTICATED_FLOW =
  'nav/DEEP_LINK_JOIN_COMMUNITY_AUTHENTENTICATED_FLOW';
export const DEEP_LINK_JOIN_COMMUNITY_UNAUTHENTENTICATED_FLOW =
  'nav/DEEP_LINK_JOIN_COMMUNITY_UNAUTHENTENTICATED_FLOW';
export const COMPLETE_STEP_FLOW = 'nav/COMPLETE_STEP_FLOW';
export const COMPLETE_STEP_FLOW_NAVIGATE_BACK =
  'nav/COMPLETE_STEP_FLOW_NAVIGATE_BACK';
export const ADD_MY_STEP_FLOW = 'nav/ADD_MY_STEP_FLOW';
export const ADD_PERSON_STEP_FLOW = 'nav/ADD_PERSON_STEP_FLOW';
export const SELECT_MY_STAGE_FLOW = 'nav/SELECT_MY_STAGE_FLOW';
export const SELECT_PERSON_STAGE_FLOW = 'nav/SELECT_PERSON_STAGE_FLOW';
export const TRY_IT_NOW_ONBOARDING_FLOW = 'nav/TRY_IT_NOW_ONBOARDING_FLOW';
