export const JOIN_BY_CODE_FLOW = 'nav/JOIN_BY_CODE_FLOW';
export const JOIN_BY_CODE_ONBOARDING_FLOW = 'nav/JOIN_BY_CODE_ONBOARDING_FLOW';
export const DEEP_LINK_JOIN_COMMUNITY_AUTHENTENTICATED_FLOW =
  'nav/DEEP_LINK_JOIN_COMMUNITY_AUTHENTENTICATED_FLOW';
export const DEEP_LINK_JOIN_COMMUNITY_UNAUTHENTENTICATED_FLOW =
  'nav/DEEP_LINK_JOIN_COMMUNITY_UNAUTHENTENTICATED_FLOW';
export const COMPLETE_STEP_FLOW = 'nav/COMPLETE_STEP_FLOW';
