platform :ios, '8.0'

target 'MissionHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MissionHub
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'

  target 'MissionHubTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
