/* eslint max-lines: 0 */

import { URL_ENCODED, URL_FORM_DATA } from '../constants';

import { API_URL, THE_KEY_URL } from './utils';

const THE_KEY_OAUTH_URL = `${THE_KEY_URL}api/oauth`;

const CHALLENGES_URL = `${API_URL}/challenges`;
const GROUP_CHALLENGE_URL = `${API_URL}/community_challenges`;
const GROUP_ACCEPTED_CHALLENGE_URL = `${API_URL}/accepted_community_challenges`;

const AUTH_URL = `${API_URL}/auth`;
const PEOPLE_URL = `${API_URL}/people`;
const SURVEY_URL = `${API_URL}/surveys`;
const ORG_URL = `${API_URL}/organizations`;

const KEY_TOKEN = {
  endpoint: `${THE_KEY_OAUTH_URL}/token`,
  method: 'post',
  extra: {
    headers: { 'Content-Type': URL_ENCODED },
  },
  stringify: false,
  anonymous: true,
  useJsonDataApiStore: false,
};

export interface ApiRouteConfigEntry {
  name: string;
  FETCH: string;
  SUCCESS: string;
  endpoint: string;
  method?: string;
  extra?: RequestInit;
  stringify?: boolean;
  useJsonDataApiStore?: boolean;
  anonymous?: boolean;
  anonymousOptional?: boolean;
  include?: string;
}

export interface ApiRouteConfig {
  [key: string]: ApiRouteConfigEntry;
}

// NOTE: Uncomment this check teporarily if _typecheck below is failing
export const REQUESTS /*: ApiRouteConfig*/ = {
  // Example
  // 'PLANETS': {
  //   method: 'get', (defaults to get)
  //   anonymous: false, (defaults to false)
  //   Put the access token on if it exists, otherwise ignore it
  //   anonymousOptional: false, (defaults to false)
  //   endpoint: 'planets/1',
  //   (gives header or other information)
  //   extra: {
  //     headers: { 'Content-Type': 'multipart/form-data' }
  //   },
  //   stringify: false,
  //   (some default data that will merge with the data passed in)
  //   data: {}
  //   (some default query that will merge with the query passed in)
  //   query: {}
  //   Don't use jsonDataApiStore
  //   useJsonDataApiStore: false
  // },
  KEY_LOGIN: {
    name: 'KEY_LOGIN' as 'KEY_LOGIN',
    FETCH: 'KEY_LOGIN_FETCH' as 'KEY_LOGIN_FETCH',
    SUCCESS: 'KEY_LOGIN_SUCCESS' as 'KEY_LOGIN_SUCCESS',
    ...KEY_TOKEN,
  },
  KEY_REFRESH_TOKEN: {
    name: 'KEY_REFRESH_TOKEN' as 'KEY_REFRESH_TOKEN',
    FETCH: 'KEY_REFRESH_TOKEN_FETCH' as 'KEY_REFRESH_TOKEN_FETCH',
    SUCCESS: 'KEY_REFRESH_TOKEN_SUCCESS' as 'KEY_REFRESH_TOKEN_SUCCESS',
    ...KEY_TOKEN,
  },
  KEY_GET_TICKET: {
    name: 'KEY_GET_TICKET' as 'KEY_GET_TICKET',
    FETCH: 'KEY_GET_TICKET_FETCH' as 'KEY_GET_TICKET_FETCH',
    SUCCESS: 'KEY_GET_TICKET_SUCCESS' as 'KEY_GET_TICKET_SUCCESS',
    endpoint: `${THE_KEY_OAUTH_URL}/ticket?service=${AUTH_URL}/thekey`,
    method: 'get',
    stringify: false,
    useJsonDataApiStore: false,
  },
  TICKET_LOGIN: {
    name: 'TICKET_LOGIN' as 'TICKET_LOGIN',
    FETCH: 'TICKET_LOGIN_FETCH' as 'TICKET_LOGIN_FETCH',
    SUCCESS: 'TICKET_LOGIN_SUCCESS' as 'TICKET_LOGIN_SUCCESS',
    endpoint: `${AUTH_URL}/thekey`,
    method: 'post',
    useJsonDataApiStore: false,
  },
  FACEBOOK_LOGIN: {
    name: 'FACEBOOK_LOGIN' as 'FACEBOOK_LOGIN',
    FETCH: 'FACEBOOK_LOGIN_FETCH' as 'FACEBOOK_LOGIN_FETCH',
    SUCCESS: 'FACEBOOK_LOGIN_SUCCESS' as 'FACEBOOK_LOGIN_SUCCESS',
    endpoint: `${AUTH_URL}/facebook`,
    method: 'post',
    useJsonDataApiStore: false,
    anonymous: true,
  },
  GET_ME: {
    name: 'GET_ME' as 'GET_ME',
    FETCH: 'GET_ME_FETCH' as 'GET_ME_FETCH',
    SUCCESS: 'GET_ME_SUCCESS' as 'GET_ME_SUCCESS',
    endpoint: `${PEOPLE_URL}/me`,
  },
  GET_UNREAD_COMMENTS_NOTIFICATION: {
    name: 'GET_UNREAD_COMMENTS_NOTIFICATION' as 'GET_UNREAD_COMMENTS_NOTIFICATION',
    FETCH: 'GET_UNREAD_COMMENTS_NOTIFICATION_FETCH' as 'GET_UNREAD_COMMENTS_NOTIFICATION_FETCH',
    SUCCESS: 'GET_UNREAD_COMMENTS_NOTIFICATION_SUCCESS' as 'GET_UNREAD_COMMENTS_NOTIFICATION_SUCCESS',
    endpoint: `${PEOPLE_URL}/me`,
  },
  GET_PERSON: {
    name: 'GET_PERSON' as 'GET_PERSON',
    FETCH: 'GET_PERSON_FETCH' as 'GET_PERSON_FETCH',
    SUCCESS: 'GET_PERSON_SUCCESS' as 'GET_PERSON_SUCCESS',
    endpoint: `${PEOPLE_URL}/:person_id`,
  },
  GET_PERSON_FEED: {
    name: 'GET_PERSON_FEED' as 'GET_PERSON_FEED',
    FETCH: 'GET_PERSON_FEED_FETCH' as 'GET_PERSON_FEED_FETCH',
    SUCCESS: 'GET_PERSON_FEED_SUCCESS' as 'GET_PERSON_FEED_SUCCESS',
    endpoint: `${API_URL}/person_feed`,
  },
  GET_STAGES: {
    name: 'GET_STAGES' as 'GET_STAGES',
    FETCH: 'GET_STAGES_FETCH' as 'GET_STAGES_FETCH',
    SUCCESS: 'GET_STAGES_SUCCESS' as 'GET_STAGES_SUCCESS',
    endpoint: `${API_URL}/pathway_stages`,
    anonymous: true,
  },
  GET_CHALLENGE_SUGGESTIONS: {
    name: 'GET_CHALLENGE_SUGGESTIONS' as 'GET_CHALLENGE_SUGGESTIONS',
    FETCH: 'GET_CHALLENGE_SUGGESTIONS_FETCH' as 'GET_CHALLENGE_SUGGESTIONS_FETCH',
    SUCCESS: 'GET_CHALLENGE_SUGGESTIONS_SUCCESS' as 'GET_CHALLENGE_SUGGESTIONS_SUCCESS',
    endpoint: `${API_URL}/challenge_suggestions`,
    anonymous: true,
  },
  ADD_CHALLENGE: {
    name: 'ADD_CHALLENGE' as 'ADD_CHALLENGE',
    FETCH: 'ADD_CHALLENGE_FETCH' as 'ADD_CHALLENGE_FETCH',
    SUCCESS: 'ADD_CHALLENGE_SUCCESS' as 'ADD_CHALLENGE_SUCCESS',
    endpoint: CHALLENGES_URL,
    method: 'post',
  },
  GET_MY_CHALLENGES: {
    name: 'GET_MY_CHALLENGES' as 'GET_MY_CHALLENGES',
    FETCH: 'GET_MY_CHALLENGES_FETCH' as 'GET_MY_CHALLENGES_FETCH',
    SUCCESS: 'GET_MY_CHALLENGES_SUCCESS' as 'GET_MY_CHALLENGES_SUCCESS',
    endpoint: CHALLENGES_URL,
  },
  DELETE_CHALLENGE: {
    name: 'DELETE_CHALLENGE' as 'DELETE_CHALLENGE',
    FETCH: 'DELETE_CHALLENGE_FETCH' as 'DELETE_CHALLENGE_FETCH',
    SUCCESS: 'DELETE_CHALLENGE_SUCCESS' as 'DELETE_CHALLENGE_SUCCESS',
    endpoint: `${CHALLENGES_URL}/:challenge_id`,
    method: 'delete',
  },
  GET_CHALLENGES_BY_FILTER: {
    name: 'GET_CHALLENGES_BY_FILTER' as 'GET_CHALLENGES_BY_FILTER',
    FETCH: 'GET_CHALLENGES_BY_FILTER_FETCH' as 'GET_CHALLENGES_BY_FILTER_FETCH',
    SUCCESS: 'GET_CHALLENGES_BY_FILTER_SUCCESS' as 'GET_CHALLENGES_BY_FILTER_SUCCESS',
    endpoint: CHALLENGES_URL,
  },
  CHALLENGE_COMPLETE: {
    name: 'CHALLENGE_COMPLETE' as 'CHALLENGE_COMPLETE',
    FETCH: 'CHALLENGE_COMPLETE_FETCH' as 'CHALLENGE_COMPLETE_FETCH',
    SUCCESS: 'CHALLENGE_COMPLETE_SUCCESS' as 'CHALLENGE_COMPLETE_SUCCESS',
    endpoint: `${CHALLENGES_URL}/:challenge_id`,
    method: 'put',
  },
  CHALLENGE_SET_FOCUS: {
    name: 'CHALLENGE_SET_FOCUS' as 'CHALLENGE_SET_FOCUS',
    FETCH: 'CHALLENGE_SET_FOCUS_FETCH' as 'CHALLENGE_SET_FOCUS_FETCH',
    SUCCESS: 'CHALLENGE_SET_FOCUS_SUCCESS' as 'CHALLENGE_SET_FOCUS_SUCCESS',
    endpoint: `${CHALLENGES_URL}/:challenge_id`,
    method: 'put',
  },
  DELETE_CHALLENGE_REMINDER: {
    name: 'DELETE_CHALLENGE_REMINDER' as 'DELETE_CHALLENGE_REMINDER',
    FETCH: 'DELETE_CHALLENGE_REMINDER_FETCH' as 'DELETE_CHALLENGE_REMINDER_FETCH',
    SUCCESS: 'DELETE_CHALLENGE_REMINDER_SUCCESS' as 'DELETE_CHALLENGE_REMINDER_SUCCESS',
    endpoint: `${CHALLENGES_URL}/:challenge_id/reminder`,
    method: 'delete',
  },
  CREATE_CHALLENGE_REMINDER: {
    name: 'CREATE_CHALLENGE_REMINDER' as 'CREATE_CHALLENGE_REMINDER',
    FETCH: 'CREATE_CHALLENGE_REMINDER_FETCH' as 'CREATE_CHALLENGE_REMINDER_FETCH',
    SUCCESS: 'CREATE_CHALLENGE_REMINDER_SUCCESS' as 'CREATE_CHALLENGE_REMINDER_SUCCESS',
    endpoint: `${CHALLENGES_URL}/:challenge_id/reminder`,
    method: 'put',
  },
  GET_PEOPLE_LIST: {
    name: 'GET_PEOPLE_LIST' as 'GET_PEOPLE_LIST',
    FETCH: 'GET_PEOPLE_LIST_FETCH' as 'GET_PEOPLE_LIST_FETCH',
    SUCCESS: 'GET_PEOPLE_LIST_SUCCESS' as 'GET_PEOPLE_LIST_SUCCESS',
    endpoint: PEOPLE_URL,
  },
  CREATE_MY_PERSON: {
    name: 'CREATE_MY_PERSON' as 'CREATE_MY_PERSON',
    FETCH: 'CREATE_MY_PERSON_FETCH' as 'CREATE_MY_PERSON_FETCH',
    SUCCESS: 'CREATE_MY_PERSON_SUCCESS' as 'CREATE_MY_PERSON_SUCCESS',
    endpoint: `${AUTH_URL}/client_token`,
    method: 'post',
    anonymous: true,
    useJsonDataApiStore: false,
  },
  REFRESH_ANONYMOUS_LOGIN: {
    name: 'REFRESH_ANONYMOUS_LOGIN' as 'REFRESH_ANONYMOUS_LOGIN',
    FETCH: 'REFRESH_ANONYMOUS_LOGIN_FETCH' as 'REFRESH_ANONYMOUS_LOGIN_FETCH',
    SUCCESS: 'REFRESH_ANONYMOUS_LOGIN_SUCCESS' as 'REFRESH_ANONYMOUS_LOGIN_SUCCESS',
    endpoint: `${AUTH_URL}/client_token`,
    method: 'post',
    anonymous: true,
    useJsonDataApiStore: false,
  },
  UPDATE_ME_USER: {
    name: 'UPDATE_ME_USER' as 'UPDATE_ME_USER',
    FETCH: 'UPDATE_ME_USER_FETCH' as 'UPDATE_ME_USER_FETCH',
    SUCCESS: 'UPDATE_ME_USER_SUCCESS' as 'UPDATE_ME_USER_SUCCESS',
    endpoint: `${API_URL}/users/me`,
    method: 'put',
  },
  ADD_NEW_PERSON: {
    name: 'ADD_NEW_PERSON' as 'ADD_NEW_PERSON',
    FETCH: 'ADD_NEW_PERSON_FETCH' as 'ADD_NEW_PERSON_FETCH',
    SUCCESS: 'ADD_NEW_PERSON_SUCCESS' as 'ADD_NEW_PERSON_SUCCESS',
    endpoint: PEOPLE_URL,
    method: 'post',
  },
  UPDATE_PERSON: {
    name: 'UPDATE_PERSON' as 'UPDATE_PERSON',
    FETCH: 'UPDATE_PERSON_FETCH' as 'UPDATE_PERSON_FETCH',
    SUCCESS: 'UPDATE_PERSON_SUCCESS' as 'UPDATE_PERSON_SUCCESS',
    endpoint: `${PEOPLE_URL}/:personId`,
    method: 'put',
  },
  GET_ORGANIZATIONS: {
    name: 'GET_ORGANIZATIONS' as 'GET_ORGANIZATIONS',
    FETCH: 'GET_ORGANIZATIONS_FETCH' as 'GET_ORGANIZATIONS_FETCH',
    SUCCESS: 'GET_ORGANIZATIONS_SUCCESS' as 'GET_ORGANIZATIONS_SUCCESS',
    endpoint: ORG_URL,
  },
  LOOKUP_COMMUNITY_CODE: {
    name: 'LOOKUP_COMMUNITY_CODE' as 'LOOKUP_COMMUNITY_CODE',
    FETCH: 'LOOKUP_COMMUNITY_CODE_FETCH' as 'LOOKUP_COMMUNITY_CODE_FETCH',
    SUCCESS: 'LOOKUP_COMMUNITY_CODE_SUCCESS' as 'LOOKUP_COMMUNITY_CODE_SUCCESS',
    endpoint: `${ORG_URL}/find_by_code`,
    anonymousOptional: true,
  },
  LOOKUP_COMMUNITY_URL: {
    name: 'LOOKUP_COMMUNITY_URL' as 'LOOKUP_COMMUNITY_URL',
    FETCH: 'LOOKUP_COMMUNITY_URL_FETCH' as 'LOOKUP_COMMUNITY_URL_FETCH',
    SUCCESS: 'LOOKUP_COMMUNITY_URL_SUCCESS' as 'LOOKUP_COMMUNITY_URL_SUCCESS',
    endpoint: `${ORG_URL}/find_by_url`,
    anonymousOptional: true,
  },
  JOIN_COMMUNITY: {
    name: 'JOIN_COMMUNITY' as 'JOIN_COMMUNITY',
    FETCH: 'JOIN_COMMUNITY_FETCH' as 'JOIN_COMMUNITY_FETCH',
    SUCCESS: 'JOIN_COMMUNITY_SUCCESS' as 'JOIN_COMMUNITY_SUCCESS',
    endpoint: `${API_URL}/organizational_permissions`,
    anonymousOptional: true,
    method: 'post',
  },
  ADD_NEW_ORGANIZATION: {
    name: 'ADD_NEW_ORGANIZATION' as 'ADD_NEW_ORGANIZATION',
    FETCH: 'ADD_NEW_ORGANIZATION_FETCH' as 'ADD_NEW_ORGANIZATION_FETCH',
    SUCCESS: 'ADD_NEW_ORGANIZATION_SUCCESS' as 'ADD_NEW_ORGANIZATION_SUCCESS',
    endpoint: ORG_URL,
    method: 'post',
  },
  GET_ORGANIZATION: {
    name: 'GET_ORGANIZATION' as 'GET_ORGANIZATION',
    FETCH: 'GET_ORGANIZATION_FETCH' as 'GET_ORGANIZATION_FETCH',
    SUCCESS: 'GET_ORGANIZATION_SUCCESS' as 'GET_ORGANIZATION_SUCCESS',
    endpoint: `${ORG_URL}/:orgId`,
  },
  UPDATE_ORGANIZATION: {
    name: 'UPDATE_ORGANIZATION' as 'UPDATE_ORGANIZATION',
    FETCH: 'UPDATE_ORGANIZATION_FETCH' as 'UPDATE_ORGANIZATION_FETCH',
    SUCCESS: 'UPDATE_ORGANIZATION_SUCCESS' as 'UPDATE_ORGANIZATION_SUCCESS',
    endpoint: `${ORG_URL}/:orgId`,
    method: 'put',
  },
  UPDATE_ORGANIZATION_IMAGE: {
    name: 'UPDATE_ORGANIZATION_IMAGE' as 'UPDATE_ORGANIZATION_IMAGE',
    FETCH: 'UPDATE_ORGANIZATION_IMAGE_FETCH' as 'UPDATE_ORGANIZATION_IMAGE_FETCH',
    SUCCESS: 'UPDATE_ORGANIZATION_IMAGE_SUCCESS' as 'UPDATE_ORGANIZATION_IMAGE_SUCCESS',
    endpoint: `${ORG_URL}/:orgId`,
    method: 'put',
    extra: {
      headers: { 'Content-Type': URL_FORM_DATA },
    },
    stringify: false,
  },
  DELETE_ORGANIZATION: {
    name: 'DELETE_ORGANIZATION' as 'DELETE_ORGANIZATION',
    FETCH: 'DELETE_ORGANIZATION_FETCH' as 'DELETE_ORGANIZATION_FETCH',
    SUCCESS: 'DELETE_ORGANIZATION_SUCCESS' as 'DELETE_ORGANIZATION_SUCCESS',
    endpoint: `${ORG_URL}/:orgId`,
    method: 'delete',
  },
  TRANSFER_ORG_OWNERSHIP: {
    name: 'TRANSFER_ORG_OWNERSHIP' as 'TRANSFER_ORG_OWNERSHIP',
    FETCH: 'TRANSFER_ORG_OWNERSHIP_FETCH' as 'TRANSFER_ORG_OWNERSHIP_FETCH',
    SUCCESS: 'TRANSFER_ORG_OWNERSHIP_SUCCESS' as 'TRANSFER_ORG_OWNERSHIP_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/community_owner`,
    method: 'put',
  },
  GET_GROUP_CELEBRATE_FEED: {
    name: 'GET_GROUP_CELEBRATE_FEED' as 'GET_GROUP_CELEBRATE_FEED',
    FETCH: 'GET_GROUP_CELEBRATE_FEED_FETCH' as 'GET_GROUP_CELEBRATE_FEED_FETCH',
    SUCCESS: 'GET_GROUP_CELEBRATE_FEED_SUCCESS' as 'GET_GROUP_CELEBRATE_FEED_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/celebration_items`,
  },
  GET_GROUP_CELEBRATE_FEED_UNREAD: {
    name: 'GET_GROUP_CELEBRATE_FEED_UNREAD' as 'GET_GROUP_CELEBRATE_FEED_UNREAD',
    FETCH: 'GET_GROUP_CELEBRATE_FEED_UNREAD_FETCH' as 'GET_GROUP_CELEBRATE_FEED_UNREAD_FETCH',
    SUCCESS: 'GET_GROUP_CELEBRATE_FEED_UNREAD_SUCCESS' as 'GET_GROUP_CELEBRATE_FEED_UNREAD_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/celebration_items`,
  },
  GET_GLOBAL_CELEBRATE_FEED: {
    name: 'GET_GLOBAL_CELEBRATE_FEED' as 'GET_GLOBAL_CELEBRATE_FEED',
    FETCH: 'GET_GLOBAL_CELEBRATE_FEED_FETCH' as 'GET_GLOBAL_CELEBRATE_FEED_FETCH',
    SUCCESS: 'GET_GLOBAL_CELEBRATE_FEED_SUCCESS' as 'GET_GLOBAL_CELEBRATE_FEED_SUCCESS',
    endpoint: `${API_URL}/global_celebration_items`,
  },
  LIKE_CELEBRATE_ITEM: {
    name: 'LIKE_CELEBRATE_ITEM' as 'LIKE_CELEBRATE_ITEM',
    FETCH: 'LIKE_CELEBRATE_ITEM_FETCH' as 'LIKE_CELEBRATE_ITEM_FETCH',
    SUCCESS: 'LIKE_CELEBRATE_ITEM_SUCCESS' as 'LIKE_CELEBRATE_ITEM_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/celebration_items/:eventId/like`,
    method: 'post',
  },
  UNLIKE_CELEBRATE_ITEM: {
    name: 'UNLIKE_CELEBRATE_ITEM' as 'UNLIKE_CELEBRATE_ITEM',
    FETCH: 'UNLIKE_CELEBRATE_ITEM_FETCH' as 'UNLIKE_CELEBRATE_ITEM_FETCH',
    SUCCESS: 'UNLIKE_CELEBRATE_ITEM_SUCCESS' as 'UNLIKE_CELEBRATE_ITEM_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/celebration_items/:eventId/like`,
    method: 'delete',
  },
  LIKE_GLOBAL_CELEBRATE_ITEM: {
    name: 'LIKE_GLOBAL_CELEBRATE_ITEM' as 'LIKE_GLOBAL_CELEBRATE_ITEM',
    FETCH: 'LIKE_GLOBAL_CELEBRATE_ITEM_FETCH' as 'LIKE_GLOBAL_CELEBRATE_ITEM_FETCH',
    SUCCESS: 'LIKE_GLOBAL_CELEBRATE_ITEM_SUCCESS' as 'LIKE_GLOBAL_CELEBRATE_ITEM_SUCCESS',
    endpoint: `${API_URL}/global_celebration_items/:eventId/like`,
    method: 'post',
  },
  UNLIKE_GLOBAL_CELEBRATE_ITEM: {
    name: 'UNLIKE_GLOBAL_CELEBRATE_ITEM' as 'UNLIKE_GLOBAL_CELEBRATE_ITEM',
    FETCH: 'UNLIKE_GLOBAL_CELEBRATE_ITEM_FETCH' as 'UNLIKE_GLOBAL_CELEBRATE_ITEM_FETCH',
    SUCCESS: 'UNLIKE_GLOBAL_CELEBRATE_ITEM_SUCCESS' as 'UNLIKE_GLOBAL_CELEBRATE_ITEM_SUCCESS',
    endpoint: `${API_URL}/global_celebration_items/:eventId/like`,
    method: 'delete',
  },
  GET_CELEBRATE_COMMENTS: {
    name: 'GET_CELEBRATE_COMMENTS' as 'GET_CELEBRATE_COMMENTS',
    FETCH: 'GET_CELEBRATE_COMMENTS_FETCH' as 'GET_CELEBRATE_COMMENTS_FETCH',
    SUCCESS: 'GET_CELEBRATE_COMMENTS_SUCCESS' as 'GET_CELEBRATE_COMMENTS_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/celebration_items/:eventId/comments`,
  },
  CREATE_CELEBRATE_COMMENT: {
    name: 'CREATE_CELEBRATE_COMMENT' as 'CREATE_CELEBRATE_COMMENT',
    FETCH: 'CREATE_CELEBRATE_COMMENT_FETCH' as 'CREATE_CELEBRATE_COMMENT_FETCH',
    SUCCESS: 'CREATE_CELEBRATE_COMMENT_SUCCESS' as 'CREATE_CELEBRATE_COMMENT_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/celebration_items/:eventId/comments`,
    method: 'post',
  },
  UPDATE_CELEBRATE_COMMENT: {
    name: 'UPDATE_CELEBRATE_COMMENT' as 'UPDATE_CELEBRATE_COMMENT',
    FETCH: 'UPDATE_CELEBRATE_COMMENT_FETCH' as 'UPDATE_CELEBRATE_COMMENT_FETCH',
    SUCCESS: 'UPDATE_CELEBRATE_COMMENT_SUCCESS' as 'UPDATE_CELEBRATE_COMMENT_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/celebration_items/:eventId/comments/:commentId`,
    method: 'put',
  },
  DELETE_CELEBRATE_COMMENT: {
    name: 'DELETE_CELEBRATE_COMMENT' as 'DELETE_CELEBRATE_COMMENT',
    FETCH: 'DELETE_CELEBRATE_COMMENT_FETCH' as 'DELETE_CELEBRATE_COMMENT_FETCH',
    SUCCESS: 'DELETE_CELEBRATE_COMMENT_SUCCESS' as 'DELETE_CELEBRATE_COMMENT_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/celebration_items/:eventId/comments/:commentId`,
    method: 'delete',
  },
  MARK_ORG_COMMENTS_AS_READ: {
    name: 'MARK_ORG_COMMENTS_AS_READ' as 'MARK_ORG_COMMENTS_AS_READ',
    FETCH: 'MARK_ORG_COMMENTS_AS_READ_FETCH' as 'MARK_ORG_COMMENTS_AS_READ_FETCH',
    SUCCESS: 'MARK_ORG_COMMENTS_AS_READ_SUCCESS' as 'MARK_ORG_COMMENTS_AS_READ_SUCCESS',
    endpoint: `${API_URL}/unread_items`,
    method: 'delete',
  },
  GET_REPORTED_COMMENTS: {
    name: 'GET_REPORTED_COMMENTS' as 'GET_REPORTED_COMMENTS',
    FETCH: 'GET_REPORTED_COMMENTS_FETCH' as 'GET_REPORTED_COMMENTS_FETCH',
    SUCCESS: 'GET_REPORTED_COMMENTS_SUCCESS' as 'GET_REPORTED_COMMENTS_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/comment_reports`,
  },
  CREATE_REPORT_COMMENT: {
    name: 'CREATE_REPORT_COMMENT' as 'CREATE_REPORT_COMMENT',
    FETCH: 'CREATE_REPORT_COMMENT_FETCH' as 'CREATE_REPORT_COMMENT_FETCH',
    SUCCESS: 'CREATE_REPORT_COMMENT_SUCCESS' as 'CREATE_REPORT_COMMENT_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/comment_reports`,
    method: 'post',
  },
  UPDATE_REPORT_COMMENT: {
    name: 'UPDATE_REPORT_COMMENT' as 'UPDATE_REPORT_COMMENT',
    FETCH: 'UPDATE_REPORT_COMMENT_FETCH' as 'UPDATE_REPORT_COMMENT_FETCH',
    SUCCESS: 'UPDATE_REPORT_COMMENT_SUCCESS' as 'UPDATE_REPORT_COMMENT_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/comment_reports/:reportCommentId`,
    method: 'put',
  },
  ORGANIZATION_NEW_CODE: {
    name: 'ORGANIZATION_NEW_CODE' as 'ORGANIZATION_NEW_CODE',
    FETCH: 'ORGANIZATION_NEW_CODE_FETCH' as 'ORGANIZATION_NEW_CODE_FETCH',
    SUCCESS: 'ORGANIZATION_NEW_CODE_SUCCESS' as 'ORGANIZATION_NEW_CODE_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/community_code`,
    method: 'put',
  },
  ORGANIZATION_NEW_LINK: {
    name: 'ORGANIZATION_NEW_LINK' as 'ORGANIZATION_NEW_LINK',
    FETCH: 'ORGANIZATION_NEW_LINK_FETCH' as 'ORGANIZATION_NEW_LINK_FETCH',
    SUCCESS: 'ORGANIZATION_NEW_LINK_SUCCESS' as 'ORGANIZATION_NEW_LINK_SUCCESS',
    endpoint: `${ORG_URL}/:orgId/community_url`,
    method: 'put',
  },
  GET_GROUP_CHALLENGE_FEED: {
    name: 'GET_GROUP_CHALLENGE_FEED' as 'GET_GROUP_CHALLENGE_FEED',
    FETCH: 'GET_GROUP_CHALLENGE_FEED_FETCH' as 'GET_GROUP_CHALLENGE_FEED_FETCH',
    SUCCESS: 'GET_GROUP_CHALLENGE_FEED_SUCCESS' as 'GET_GROUP_CHALLENGE_FEED_SUCCESS',
    endpoint: GROUP_CHALLENGE_URL,
  },
  ACCEPT_GROUP_CHALLENGE: {
    name: 'ACCEPT_GROUP_CHALLENGE' as 'ACCEPT_GROUP_CHALLENGE',
    FETCH: 'ACCEPT_GROUP_CHALLENGE_FETCH' as 'ACCEPT_GROUP_CHALLENGE_FETCH',
    SUCCESS: 'ACCEPT_GROUP_CHALLENGE_SUCCESS' as 'ACCEPT_GROUP_CHALLENGE_SUCCESS',
    endpoint: GROUP_ACCEPTED_CHALLENGE_URL,
    method: 'post',
  },
  COMPLETE_GROUP_CHALLENGE: {
    name: 'COMPLETE_GROUP_CHALLENGE' as 'COMPLETE_GROUP_CHALLENGE',
    FETCH: 'COMPLETE_GROUP_CHALLENGE_FETCH' as 'COMPLETE_GROUP_CHALLENGE_FETCH',
    SUCCESS: 'COMPLETE_GROUP_CHALLENGE_SUCCESS' as 'COMPLETE_GROUP_CHALLENGE_SUCCESS',
    endpoint: `${GROUP_ACCEPTED_CHALLENGE_URL}/:challengeId`,
    method: 'put',
  },
  UPDATE_GROUP_CHALLENGE: {
    name: 'UPDATE_GROUP_CHALLENGE' as 'UPDATE_GROUP_CHALLENGE',
    FETCH: 'UPDATE_GROUP_CHALLENGE_FETCH' as 'UPDATE_GROUP_CHALLENGE_FETCH',
    SUCCESS: 'UPDATE_GROUP_CHALLENGE_SUCCESS' as 'UPDATE_GROUP_CHALLENGE_SUCCESS',
    endpoint: `${GROUP_CHALLENGE_URL}/:challenge_id`,
    method: 'put',
  },
  CREATE_GROUP_CHALLENGE: {
    name: 'CREATE_GROUP_CHALLENGE' as 'CREATE_GROUP_CHALLENGE',
    FETCH: 'CREATE_GROUP_CHALLENGE_FETCH' as 'CREATE_GROUP_CHALLENGE_FETCH',
    SUCCESS: 'CREATE_GROUP_CHALLENGE_SUCCESS' as 'CREATE_GROUP_CHALLENGE_SUCCESS',
    endpoint: GROUP_CHALLENGE_URL,
    method: 'post',
  },
  GET_GROUP_CHALLENGE: {
    name: 'GET_GROUP_CHALLENGE' as 'GET_GROUP_CHALLENGE',
    FETCH: 'GET_GROUP_CHALLENGE_FETCH' as 'GET_GROUP_CHALLENGE_FETCH',
    SUCCESS: 'GET_GROUP_CHALLENGE_SUCCESS' as 'GET_GROUP_CHALLENGE_SUCCESS',
    endpoint: `${GROUP_CHALLENGE_URL}/:challenge_id`,
  },
  GET_MY_GROUPS: {
    name: 'GET_MY_GROUPS' as 'GET_MY_GROUPS',
    FETCH: 'GET_MY_GROUPS_FETCH' as 'GET_MY_GROUPS_FETCH',
    SUCCESS: 'GET_MY_GROUPS_SUCCESS' as 'GET_MY_GROUPS_SUCCESS',
    endpoint: `${API_URL}/groups`,
  },
  GET_SURVEY_QUESTIONS: {
    name: 'GET_SURVEY_QUESTIONS' as 'GET_SURVEY_QUESTIONS',
    FETCH: 'GET_SURVEY_QUESTIONS_FETCH' as 'GET_SURVEY_QUESTIONS_FETCH',
    SUCCESS: 'GET_SURVEY_QUESTIONS_SUCCESS' as 'GET_SURVEY_QUESTIONS_SUCCESS',
    endpoint: `${SURVEY_URL}/:surveyId/questions`,
  },
  GET_SURVEYS: {
    name: 'GET_SURVEYS' as 'GET_SURVEYS',
    FETCH: 'GET_SURVEYS_FETCH' as 'GET_SURVEYS_FETCH',
    SUCCESS: 'GET_SURVEYS_SUCCESS' as 'GET_SURVEYS_SUCCESS',
    endpoint: SURVEY_URL,
  },
  GET_GROUP_SURVEYS: {
    name: 'GET_GROUP_SURVEYS' as 'GET_GROUP_SURVEYS',
    FETCH: 'GET_GROUP_SURVEYS_FETCH' as 'GET_GROUP_SURVEYS_FETCH',
    SUCCESS: 'GET_GROUP_SURVEYS_SUCCESS' as 'GET_GROUP_SURVEYS_SUCCESS',
    endpoint: SURVEY_URL,
  },
  GET_FILTER_STATS: {
    name: 'GET_FILTER_STATS' as 'GET_FILTER_STATS',
    FETCH: 'GET_FILTER_STATS_FETCH' as 'GET_FILTER_STATS_FETCH',
    SUCCESS: 'GET_FILTER_STATS_SUCCESS' as 'GET_FILTER_STATS_SUCCESS',
    endpoint: `${API_URL}/filter_stats/survey`,
  },
  GET_MY_LABELS: {
    name: 'GET_MY_LABELS' as 'GET_MY_LABELS',
    FETCH: 'GET_MY_LABELS_FETCH' as 'GET_MY_LABELS_FETCH',
    SUCCESS: 'GET_MY_LABELS_SUCCESS' as 'GET_MY_LABELS_SUCCESS',
    endpoint: ORG_URL,
    include: 'labels',
  },
  GET_ORGANIZATION_LABELS: {
    name: 'GET_ORGANIZATION_LABELS' as 'GET_ORGANIZATION_LABELS',
    FETCH: 'GET_ORGANIZATION_LABELS_FETCH' as 'GET_ORGANIZATION_LABELS_FETCH',
    SUCCESS: 'GET_ORGANIZATION_LABELS_SUCCESS' as 'GET_ORGANIZATION_LABELS_SUCCESS',
    endpoint: `${ORG_URL}/:orgId`,
  },
  GET_IMPACT_SUMMARY: {
    name: 'GET_IMPACT_SUMMARY' as 'GET_IMPACT_SUMMARY',
    FETCH: 'GET_IMPACT_SUMMARY_FETCH' as 'GET_IMPACT_SUMMARY_FETCH',
    SUCCESS: 'GET_IMPACT_SUMMARY_SUCCESS' as 'GET_IMPACT_SUMMARY_SUCCESS',
    endpoint: `${API_URL}/reports/impact`,
  },
  GET_PEOPLE_INTERACTIONS_REPORT: {
    name: 'GET_PEOPLE_INTERACTIONS_REPORT' as 'GET_PEOPLE_INTERACTIONS_REPORT',
    FETCH: 'GET_PEOPLE_INTERACTIONS_REPORT_FETCH' as 'GET_PEOPLE_INTERACTIONS_REPORT_FETCH',
    SUCCESS: 'GET_PEOPLE_INTERACTIONS_REPORT_SUCCESS' as 'GET_PEOPLE_INTERACTIONS_REPORT_SUCCESS',
    endpoint: `${API_URL}/reports/people`,
  },
  GET_ORGANIZATION_INTERACTIONS_REPORT: {
    name: 'GET_ORGANIZATION_INTERACTIONS_REPORT' as 'GET_ORGANIZATION_INTERACTIONS_REPORT',
    FETCH: 'GET_ORGANIZATION_INTERACTIONS_REPORT_FETCH' as 'GET_ORGANIZATION_INTERACTIONS_REPORT_FETCH',
    SUCCESS: 'GET_ORGANIZATION_INTERACTIONS_REPORT_SUCCESS' as 'GET_ORGANIZATION_INTERACTIONS_REPORT_SUCCESS',
    endpoint: `${API_URL}/reports/organizations`,
  },
  GET_USERS_REPORT: {
    name: 'GET_USERS_REPORT' as 'GET_USERS_REPORT',
    FETCH: 'GET_USERS_REPORT_FETCH' as 'GET_USERS_REPORT_FETCH',
    SUCCESS: 'GET_USERS_REPORT_SUCCESS' as 'GET_USERS_REPORT_SUCCESS',
    endpoint: `${API_URL}/reports/users`,
  },
  SET_PUSH_TOKEN: {
    name: 'SET_PUSH_TOKEN' as 'SET_PUSH_TOKEN',
    FETCH: 'SET_PUSH_TOKEN_FETCH' as 'SET_PUSH_TOKEN_FETCH',
    SUCCESS: 'SET_PUSH_TOKEN_SUCCESS' as 'SET_PUSH_TOKEN_SUCCESS',
    endpoint: `${API_URL}/push_notification_device_tokens`,
    method: 'post',
  },
  DELETE_PUSH_TOKEN: {
    name: 'DELETE_PUSH_TOKEN' as 'DELETE_PUSH_TOKEN',
    FETCH: 'DELETE_PUSH_TOKEN_FETCH' as 'DELETE_PUSH_TOKEN_FETCH',
    SUCCESS: 'DELETE_PUSH_TOKEN_SUCCESS' as 'DELETE_PUSH_TOKEN_SUCCESS',
    endpoint: `${API_URL}/push_notification_device_tokens/:deviceId`,
    method: 'delete',
  },
  CREATE_CONTACT_ASSIGNMENT: {
    name: 'CREATE_CONTACT_ASSIGNMENT' as 'CREATE_CONTACT_ASSIGNMENT',
    FETCH: 'CREATE_CONTACT_ASSIGNMENT_FETCH' as 'CREATE_CONTACT_ASSIGNMENT_FETCH',
    SUCCESS: 'CREATE_CONTACT_ASSIGNMENT_SUCCESS' as 'CREATE_CONTACT_ASSIGNMENT_SUCCESS',
    endpoint: `${API_URL}/contact_assignments`,
    method: 'post',
  },
  UPDATE_CONTACT_ASSIGNMENT: {
    name: 'UPDATE_CONTACT_ASSIGNMENT' as 'UPDATE_CONTACT_ASSIGNMENT',
    FETCH: 'UPDATE_CONTACT_ASSIGNMENT_FETCH' as 'UPDATE_CONTACT_ASSIGNMENT_FETCH',
    SUCCESS: 'UPDATE_CONTACT_ASSIGNMENT_SUCCESS' as 'UPDATE_CONTACT_ASSIGNMENT_SUCCESS',
    endpoint: `${API_URL}/contact_assignments/:contactAssignmentId`,
    method: 'put',
  },
  DELETE_CONTACT_ASSIGNMENT: {
    name: 'DELETE_CONTACT_ASSIGNMENT' as 'DELETE_CONTACT_ASSIGNMENT',
    FETCH: 'DELETE_CONTACT_ASSIGNMENT_FETCH' as 'DELETE_CONTACT_ASSIGNMENT_FETCH',
    SUCCESS: 'DELETE_CONTACT_ASSIGNMENT_SUCCESS' as 'DELETE_CONTACT_ASSIGNMENT_SUCCESS',
    endpoint: `${API_URL}/contact_assignments/:contactAssignmentId`,
    method: 'delete',
  },
  ADD_NEW_INTERACTION: {
    name: 'ADD_NEW_INTERACTION' as 'ADD_NEW_INTERACTION',
    FETCH: 'ADD_NEW_INTERACTION_FETCH' as 'ADD_NEW_INTERACTION_FETCH',
    SUCCESS: 'ADD_NEW_INTERACTION_SUCCESS' as 'ADD_NEW_INTERACTION_SUCCESS',
    endpoint: `${API_URL}/interactions`,
    method: 'post',
  },
  EDIT_COMMENT: {
    name: 'EDIT_COMMENT' as 'EDIT_COMMENT',
    FETCH: 'EDIT_COMMENT_FETCH' as 'EDIT_COMMENT_FETCH',
    SUCCESS: 'EDIT_COMMENT_SUCCESS' as 'EDIT_COMMENT_SUCCESS',
    endpoint: `${API_URL}/interactions/:interactionId`,
    method: 'put',
  },
  SEARCH: {
    name: 'SEARCH' as 'SEARCH',
    FETCH: 'SEARCH_FETCH' as 'SEARCH_FETCH',
    SUCCESS: 'SEARCH_SUCCESS' as 'SEARCH_SUCCESS',
    endpoint: `${API_URL}/search`,
  },
  ADD_PERSON_NOTE: {
    name: 'ADD_PERSON_NOTE' as 'ADD_PERSON_NOTE',
    FETCH: 'ADD_PERSON_NOTE_FETCH' as 'ADD_PERSON_NOTE_FETCH',
    SUCCESS: 'ADD_PERSON_NOTE_SUCCESS' as 'ADD_PERSON_NOTE_SUCCESS',
    endpoint: `${API_URL}/person_notes`,
    method: 'post',
  },
  UPDATE_PERSON_NOTE: {
    name: 'UPDATE_PERSON_NOTE' as 'UPDATE_PERSON_NOTE',
    FETCH: 'UPDATE_PERSON_NOTE_FETCH' as 'UPDATE_PERSON_NOTE_FETCH',
    SUCCESS: 'UPDATE_PERSON_NOTE_SUCCESS' as 'UPDATE_PERSON_NOTE_SUCCESS',
    endpoint: `${API_URL}/person_notes/:noteId`,
    method: 'put',
  },
  GET_PERSON_NOTE: {
    name: 'GET_PERSON_NOTE' as 'GET_PERSON_NOTE',
    FETCH: 'GET_PERSON_NOTE_FETCH' as 'GET_PERSON_NOTE_FETCH',
    SUCCESS: 'GET_PERSON_NOTE_SUCCESS' as 'GET_PERSON_NOTE_SUCCESS',
    endpoint: `${PEOPLE_URL}/:person_id`,
  },
  GET_ANSWER_SHEETS: {
    name: 'GET_ANSWER_SHEETS' as 'GET_ANSWER_SHEETS',
    FETCH: 'GET_ANSWER_SHEETS_FETCH' as 'GET_ANSWER_SHEETS_FETCH',
    SUCCESS: 'GET_ANSWER_SHEETS_SUCCESS' as 'GET_ANSWER_SHEETS_SUCCESS',
    endpoint: `${API_URL}/answer_sheets`,
  },
};

// NOTE: If this typecheck is failing, temporarily enable the check above on apiRoutes to find the issue
const _typecheck: ApiRouteConfig = REQUESTS;
_typecheck;
