/** Declaration file generated by dts-gen */

declare module 'jsonapi-datastore' {
  export class JsonApiDataStore {
    constructor();

    destroy(model: any): void;

    find(type: any, id: any): any;

    findAll(type: any): any;

    initModel(type: any, id: any): any;

    reset(): void;

    sync(payload: any): any;

    syncRecord(rec: any): any;

    syncWithMeta(payload: any): any;
  }

  export class JsonApiDataStoreModel {
    constructor(type: any, id: any);

    serialize(opts: any): any;

    setAttribute(attrName: any, value: any): void;

    setRelationship(relName: any, models: any): void;
  }

  export namespace JsonApiDataStore {
    namespace prototype {
      function destroy(model: any): void;

      function find(type: any, id: any): any;

      function findAll(type: any): any;

      function initModel(type: any, id: any): any;

      function reset(): void;

      function sync(payload: any): any;

      function syncRecord(rec: any): any;

      function syncWithMeta(payload: any): any;

      namespace destroy {
        const prototype: {};
      }

      namespace find {
        const prototype: {};
      }

      namespace findAll {
        const prototype: {};
      }

      namespace initModel {
        const prototype: {};
      }

      namespace reset {
        const prototype: {};
      }

      namespace sync {
        const prototype: {};
      }

      namespace syncRecord {
        const prototype: {};
      }

      namespace syncWithMeta {
        const prototype: {};
      }
    }
  }

  export namespace JsonApiDataStoreModel {
    namespace prototype {
      function serialize(opts: any): any;

      function setAttribute(attrName: any, value: any): void;

      function setRelationship(relName: any, models: any): void;

      namespace serialize {
        const prototype: {};
      }

      namespace setAttribute {
        const prototype: {};
      }

      namespace setRelationship {
        const prototype: {};
      }
    }
  }
}
