# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    # increment_build_number(xcodeproj: "MissionHub.xcodeproj")
    # build_app(scheme: "MissionHub")
    # upload_to_app_store
  end
  
  desc "Push a new (beta) release build to Crashlytics"
  lane :beta do
    increment_build_number(xcodeproj: "MissionHub.xcodeproj")

    # create_keychain(
    #     name: ENV["MATCH_KEYCHAIN_NAME"],
    #     password: ENV["MATCH_PASSWORD"],
    #     default_keychain: true,
    #     unlock: true,
    #     timeout: 3600,
    #     add_to_search_list: true
    # )

    # match(readonly: true,
    #       keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
    #       keychain_password: ENV["MATCH_PASSWORD"])

    # gym(
    #     scheme: "MissionHub",
    #     export_method: "ad-hoc",
    #     skip_package_ipa: "true",
    #
    #     export_options: {
    #     provisioningProfiles: {
    #     "com.missionhub" => "match AdHoc com.missionhub"
    #     }
    #   }
    # )

    # crashlytics(
    #             crashlytics_path: "./Crashlytics.framework",
    #             ipa_path: "./MissionHub.ipa",
    #             groups: "missionhub-ios",
    #             notes_path: "./release_notes/releaseNotes.txt"
    # )

    # git_commit(
    #     path: %w[MissionHub/Info.plist MissionHub.xcodeproj/project.pbxproj],
    #     message: 'Build number bump'
    # )

    commit_version_bump(
        xcodeproj: 'MissionHub.xcodeproj',
        message: 'Build number bump'
    )

    push_to_git_remote(
        local_branch: 'MHP-1314-Fastlane-Travis',
    )

    # hipchat(
    #         message: "MissionHub iOS Beta build released to Crashlytics.",
    #         channel: "MissionHub - Engineering",
    #         version: "2",
    #         custom_color: "green"
    # )
    end
end
