# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
require 'json'

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do

    cru_build_app

    api_json_file = File.read('GooglePlayAPI.json')
    api_json_hash = JSON.parse(api_json_file)
    api_json_hash['private_key'] = ENV['GOOGLE_PLAY_API_PRIVATE_KEY']

    upload_to_play_store(track: 'beta',
                         json_key_data: api_json_hash.to_json,
                         skip_upload_metadata: true,
                         skip_upload_screenshots: true,
                         skip_upload_images: true)

    cru_notify_users(message: "MissionHub Android Beta Build released to Play Store Beta Channel.")
  end

  lane :cru_build_app do
    gradle(task: "clean assembleRelease")
  end

  lane :cru_notify_users do |options|
    hipchat(
        message: options[:message],
        channel: "MissionHub - Engineering",
        version: "2",
        custom_color: "green"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease",
           print_command: false)
    upload_to_play_store
  end
end
