# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do

    cru_build_app
    
    crashlytics(
        apk_path: ENV['GRADLE_APK_OUTPUT_PATH'],
        groups: 'missionhub-android',
        notes: 'Beta build for MissionHub Android. See Jira board for issues that are "Ready for QA"'
    )

    cru_notify_users(message: "MissionHub Android Beta Build released to Crashlytics.")
  end

  lane :cru_build_app do

    begin
      # if there is a local .env file, move it to a backup.
      sh('mv -f ../../.env ../../.env.bkup')
    rescue
      puts "The droid (file) we were looking for wasn't there. We can go about our business... Move along.."
    end

    sh('cp', '../../.env.production', '../../.env')

    gradle(task: "clean assembleRelease")

    # if there is a backup .env file created above, put it back.
    # don't fail if it isn't there though.
    begin
      sh('mv -f ../../.env.bkup ../../.env')
    rescue
      puts "The droid (file) we were looking for wasn't there. We can go about our business... Move along.."
    end
  end

  lane :cru_notify_users do |options|
    hipchat(
        message: options[:message],
        channel: "MissionHub - Engineering",
        version: "2",
        custom_color: "green"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
